export const addressInputs = [
  {
    id: 1,
    name: 'contactName',
    type: 'text',
    placeholder: 'Enter name of contact person',
    label: 'Contact person name',
  },
  {
    id: 2,
    name: 'street1',
    type: 'text',
    placeholder: 'Enter H.No./Street',
    label: 'H.No./Street',
  },
  {
    id: 3,
    name: 'street2',
    type: 'text',
    placeholder: 'Enter area / locality',
    label: 'Area/locality',
  },
  {
    id: 4,
    name: 'city',
    type: 'text',
    placeholder: 'Enter city',
    label: 'City',
  },
  {
    id: 5,
    name: 'state',
    type: 'text',
    placeholder: 'Enter state',
    label: 'State',
  },
  {
    id: 6,
    name: 'pincode',
    type: 'text',
    placeholder: 'Enter pincode',
    label: 'Pincode (e.g. 560037)',
  },
  {
    id: 7,
    name: 'country',
    type: 'text',
    placeholder: 'Enter country',
    label: 'Country',
  },
  {
    id: 8,
    name: 'phone',
    type: 'text',
    placeholder: 'Enter contact no.',
    label: 'Phone (e.g. 9876512345)',
  },
];
